<a href="https://colab.research.google.com/github/NATO-dotcom/ML-AI_Python/blob/main/pokesman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data =pd.read_csv('/pokemon data.csv')

In [ ]:
data

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
data.head(10)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False

In [ ]:
data.tail()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
data.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [ ]:
data['Attack']

0       49
1       62
2       82
3      100
4       52
      ...
795    100
796    160
797    110
798    160
799    110
Name: Attack, Length: 800, dtype: int64

In [ ]:
data.loc[data['Attack']]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
62,57,Primeape,Fighting,NaN,65,105,60,60,70,95,1,False
82,76,Golem,Rock,Ground,80,120,130,55,65,45,1,False
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False
52,47,Parasect,Bug,Grass,60,95,80,60,80,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False
160,148,Dragonair,Dragon,NaN,61,84,65,70,70,70,1,False
110,102,Exeggcute,Grass,Psychic,60,40,80,60,45,40,1,False
160,148,Dragonair,Dragon,NaN,61,84,65,70,70,70,1,False
110,102,Exeggcute,Grass,Psychic,60,40,80,60,45,40,1,False

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

In [ ]:
data.shape#no.of rows and columns

(800, 12)

In [ ]:
data.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
data.duplicated().sum()

0

In [ ]:
data.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

In [ ]:
data.dtypes.value_counts()

int64     8
object    3
bool      1
Name: count, dtype: int64

In [ ]:
data.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [ ]:
data.loc[2,'Attack']

82

In [ ]:
data.iloc[2,3]

'Poison'

In [ ]:
data['Attack'].mean()

np.float64(79.00125)

In [ ]:
data['Defense'].mode()

0    70
Name: Defense, dtype: int64

In [ ]:
data.iloc[1,1]

'Ivysaur'

In [ ]:
data['Attack'].unique()

array([ 49,  62,  82, 100,  52,  64,  84, 130, 104,  48,  63,  83, 103,
        30,  20,  45,  35,  25,  90, 150,  60,  80,  56,  81,  85,  55,
        75,  47,  92,  57,  72, 102,  70,  41,  76,  50,  65,  95, 105,
       110,  40, 120,  73,   5, 125,  67, 155,  10, 115, 135, 134, 190,
        46,  38,  58,  33, 185, 164, 160,  51,  71,  91, 140,  43,  78,
        15, 165,  68,  23, 145, 180,  89, 109,  66,  86,  42,  29,  59,
        79,  69,  94, 136,  93,  24, 170, 112,  61, 106, 132, 123,  88,
        53,  98,  77,  27, 117, 108,  44,  87, 147,  74, 124,  97, 129,
       128, 107,  36,  22,  54, 121, 131])

In [ ]:
data['Attack']

0       49
1       62
2       82
3      100
4       52
      ...
795    100
796    160
797    110
798    160
799    110
Name: Attack, Length: 800, dtype: int64

In [ ]:
data['Attack'].dtype

dtype('int64')

In [ ]:
data['Attack'].value_counts()

Attack
100    40
65     39
80     37
50     37
60     33
       ..
128     1
36      1
22      1
54      1
121     1
Name: count, Length: 111, dtype: int64

In [ ]:
data['Attack'].value_counts(normalize=True)

Attack
100    0.05000
65     0.04875
80     0.04625
50     0.04625
60     0.04125
        ...
128    0.00125
36     0.00125
22     0.00125
54     0.00125
121    0.00125
Name: proportion, Length: 111, dtype: float64